package com.qf.oa.dao;

import com.qf.oa.entity.Resc;

import java.util.List;

public interface RescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resc
     *
     * @mbggenerated
     */
    int insert(Resc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resc
     *
     * @mbggenerated
     */
    int insertSelective(Resc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resc
     *
     * @mbggenerated
     */
    Resc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Resc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Resc record);

    List<Resc> queryAll();

    /**
     * 根据角色id查询权限
     * @param rid
     * @return
     */
    List<Resc> queryAllByRid(Integer rid);
}