package com.qf.oa.dao;

import com.qf.oa.entity.Role;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);

    List<Role> queryAll();

    /**
     * 根据eid查询员工所拥有角色
     *
     * @param eid
     * @return
     */
    List<Role> queryRoleByEid(Integer eid);

    /**
     * 查询所有角色，标记查询员工所拥有的角色
     *
     * @param eid
     * @return
     */
    List<Role> queryAllByEid(Integer eid);

    int deleteRescByRid(Integer rid);

    int addRoleResc(@Param("rid") Integer rid, @Param("reids") Integer[] reids);

}